from typing import Annotated, Sequence, Dict
from datetime import date, timedelta, datetime
from typing_extensions import TypedDict, Optional
from langchain_openai import ChatOpenAI
from tradingagents.agents import *
from langgraph.prebuilt import ToolNode
from langgraph.graph import END, StateGraph, START, MessagesState


# Analyst structured report format for traceability and noise reduction
class AnalystReport(TypedDict):
    analyst_name: str
    summary: str  # 专业详细的中文分析报告
    key_metrics: Annotated[dict, "Dictionary of critical metrics/indicators found"]
    decision: Annotated[str, "Internal stance: BUY, SELL, or HOLD"]
    confidence: float # 0.0 to 1.0 (置信度)
    risk_score: float # 0.0 to 1.0 (风险指数，1.0为极高风险)
    risk_bias: Annotated[str, "Strategic bias: aggressive, neutral, or conservative"]


# Researcher team state
class InvestDebateState(TypedDict):
    bull_history: Annotated[str, "Bullish Conversation history"]
    bear_history: Annotated[str, "Bearish Conversation history"]
    history: Annotated[str, "Conversation history"]
    current_response: Annotated[str, "Latest response"]
    judge_decision: Annotated[str, "Final judge decision"]
    count: Annotated[int, "Length of the current conversation"]


# Risk management team state
class RiskDebateState(TypedDict):
    aggressive_history: Annotated[str, "Aggressive Agent's Conversation history"]
    conservative_history: Annotated[str, "Conservative Agent's Conversation history"]
    neutral_history: Annotated[str, "Neutral Agent's Conversation history"]
    history: Annotated[str, "Conversation history"]
    latest_speaker: Annotated[str, "Analyst that spoke last"]
    current_aggressive_response: Annotated[str, "Latest response by the aggressive analyst"]
    current_conservative_response: Annotated[str, "Latest response by the conservative analyst"]
    current_neutral_response: Annotated[str, "Latest response by the neutral analyst"]
    judge_decision: Annotated[str, "Judge's decision"]
    count: Annotated[int, "Length of the current conversation"]


class AgentState(MessagesState):
    company_of_interest: Annotated[str, "Company that we are interested in trading"]
    trade_date: Annotated[str, "What date we are trading at"]
    sender: Annotated[str, "Agent that sent this message"]

    # Structured storage for analyst outputs (The primary source of truth for managers)
    structured_reports: Annotated[Dict[str, AnalystReport], "Repository for all processed node outputs"]

    # legacy/preview fields (kept for backward compatibility where nodes haven't been refactored)
    market_report: Annotated[str, "Report from the Market Analyst"]
    sentiment_report: Annotated[str, "Report from the Social Media Analyst"]
    news_report: Annotated[str, "Report from the News Researcher"]
    fundamentals_report: Annotated[str, "Report from the Fundamentals Researcher"]
    kronos_report: Annotated[str, "AI Prediction report from Kronos model"]

    # researcher team discussion step
    investment_debate_state: Annotated[InvestDebateState, "Current state of the debate"]
    investment_plan: Annotated[str, "Plan generated by the Analyst"]
    trader_investment_plan: Annotated[str, "Plan generated by the Trader"]

    # risk management team discussion step
    risk_debate_state: Annotated[RiskDebateState, "Current state of the debate"]
    final_trade_decision: Annotated[str, "Final decision made by the Risk Analysts"]
